# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2020-01-16 04:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200115_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('monto', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=300)),
            ],
        ),
    ]
