# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2020-01-17 00:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200116_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
