# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2020-03-10 08:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200301_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminpaq', models.CharField(blank=True, max_length=400, null=True)),
                ('razonsocial', models.CharField(blank=True, max_length=400, null=True)),
                ('rfc', models.CharField(blank=True, max_length=400, null=True)),
                ('direccioncompleta', models.CharField(blank=True, max_length=400, null=True)),
                ('coloniatxt', models.CharField(blank=True, max_length=400, null=True)),
                ('calle', models.CharField(blank=True, max_length=400, null=True)),
                ('numeroexterior', models.CharField(blank=True, max_length=400, null=True)),
                ('numerointerior', models.CharField(blank=True, max_length=400, null=True)),
                ('cp', models.CharField(blank=True, max_length=400, null=True)),
                ('creacion', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('lunes', models.BooleanField(default=False)),
                ('martes', models.BooleanField(default=False)),
                ('miercoles', models.BooleanField(default=False)),
                ('jueves', models.BooleanField(default=False)),
                ('viernes', models.BooleanField(default=False)),
                ('sabado', models.BooleanField(default=False)),
                ('domingo', models.BooleanField(default=False)),
                ('email', models.CharField(blank=True, max_length=400, null=True)),
                ('telefono', models.CharField(blank=True, max_length=400, null=True)),
                ('denominacion', models.CharField(blank=True, max_length=400, null=True)),
                ('representante', models.CharField(blank=True, max_length=400, null=True)),
                ('estadotxt', models.CharField(blank=True, max_length=400, null=True)),
                ('ciudadtxt', models.CharField(blank=True, max_length=400, null=True)),
                ('nombrecomercialtxt', models.CharField(blank=True, max_length=400, null=True)),
                ('ciudad', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='estado', chained_model_field='estado', null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.Ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=400, null=True)),
                ('creacion', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.Estado'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipocliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.TipoCliente'),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='estado',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='pais', chained_model_field='pais', null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.Estado'),
        ),
    ]
