# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2020-03-10 10:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20200310_0206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='adminpaq',
            new_name='codigo',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='ciudadtxt',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='denominacion',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='estadotxt',
        ),
    ]
