# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2020-03-10 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20200310_0406'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=400, null=True)),
                ('lat', models.CharField(blank=True, max_length=100, null=True)),
                ('lon', models.CharField(blank=True, max_length=100, null=True)),
                ('calle', models.CharField(blank=True, max_length=400, null=True)),
                ('numeroexterior', models.CharField(blank=True, max_length=400, null=True)),
                ('numerointerior', models.CharField(blank=True, max_length=400, null=True)),
                ('cp', models.CharField(blank=True, max_length=400, null=True)),
                ('telefono', models.CharField(blank=True, max_length=400, null=True)),
                ('representante', models.CharField(blank=True, max_length=400, null=True)),
                ('ciudad', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='estado', chained_model_field='estado', null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.Ciudad')),
                ('estado', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.Estado')),
            ],
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='grado',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='grupo',
        ),
        migrations.DeleteModel(
            name='Gasto',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='alumno',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='coloniatxt',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='representante',
        ),
        migrations.DeleteModel(
            name='Alumno',
        ),
        migrations.DeleteModel(
            name='Grado',
        ),
        migrations.DeleteModel(
            name='Grupo',
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
    ]
