# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2020-03-10 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20200310_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.Cliente'),
        ),
    ]
