# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2020-03-11 09:58
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_sucursal_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='estado',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.Estado'),
        ),
    ]
