# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2020-03-11 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20200311_0459'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='ocultar',
            field=models.BooleanField(default=False),
        ),
    ]
