# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2020-03-12 00:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20200311_0812'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=400, null=True)),
                ('pendiente', models.BooleanField(default=False)),
                ('completa', models.BooleanField(default=False)),
                ('cancelada', models.BooleanField(default=False)),
                ('fechalimite', models.DateTimeField(blank=True, null=True)),
                ('comentario', models.CharField(blank=True, max_length=400, null=True)),
                ('fechacancelado', models.DateTimeField(blank=True, null=True)),
                ('fechaterminado', models.DateTimeField(blank=True, null=True)),
                ('creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignado', to='blog.Usuario')),
                ('creador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='creado', to='blog.Usuario')),
            ],
        ),
    ]
