# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2020-03-12 03:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_tarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=400, null=True)),
                ('puesto', models.CharField(blank=True, max_length=400, null=True)),
                ('email', models.CharField(blank=True, max_length=400, null=True)),
                ('telefono', models.CharField(blank=True, max_length=400, null=True)),
                ('extension', models.CharField(blank=True, max_length=400, null=True)),
                ('creacion', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('colonia', models.CharField(blank=True, max_length=400, null=True)),
                ('cp', models.CharField(blank=True, max_length=400, null=True)),
                ('calle', models.CharField(blank=True, max_length=400, null=True)),
                ('entrecalles', models.CharField(blank=True, max_length=400, null=True)),
                ('ciudad', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='estado', chained_model_field='estado', null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.Ciudad')),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.Estado')),
            ],
        ),
    ]
