# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2020-03-12 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_contacto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='entrecalles',
        ),
        migrations.AddField(
            model_name='orden',
            name='fecha_limite',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
